### ISSUE TITLE
Add support to directly convert from other file formats to pdf

### ISSUE THREAD

**Issue by ZeroDot1** [mbedded/pdfmerge#2]
E.g. if you have a folder with several .png or .jpg files it would be very good if you just have to specify the path and pdfmerge does the rest.
![Bildschirmfoto vom 2021-01-30 15-19-48](https://user-images.githubusercontent.com/28985171/106358787-9ecf2680-630e-11eb-8ce0-d69686382eb8.png)

**Comment by mbedded** [comment]
Hello Zerodot,

unfortunately this tool does not aim to convert any files. For this usage i recommend other tools like `imagemagick`.
There you can convert your files using `convert image.png output.pdf` and use the output file for merging.

To do so, you may have to adjust your configuration for Imagemagick:
```
nano /etc/ImageMagick-6/policy.xml
```

Change `<policy domain="coder" rights="none" pattern="PDF" />`
to `<policy domain="coder" rights="read|write" pattern="PDF" />`
and save your settings.
